- name: install and run nginx
  hosts: web
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
